name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        if: github.ref == 'refs/heads/master'
        uses: matootie/github-docker@v2.2.2
        with:
          accessToken: ${{github.token}}
          imageTag: latest
